hydra:
  run:
    dir: '.'

model_type: &mtype unet_segm+int

defaults:
  - model: *mtype

checkpoints: ./checkpoints
work_dir: ./runs
out_dir: ./outputs
data_path: ../synthetic_dataset
real_path: ../raw_dataset/Test/Test/full_annotations.csv

project_name: unet_int_mask
experiment_name: unet_int_mask_local

seed: 2025
n_workers: 0
accelerator: 'gpu'
device: 0
log_nsteps: 20

batch_size: 8
n_epochs: 40

dataset:
  train_size: 0.8
  image_width: 640
  image_height: 640
